### ISSUE TITLE
PKEY path wrong

### ISSUE THREAD

**Issue by shirleyzhou94** [Azure/azhpc-diagnostics#19]
I was investigating an incident involves IB & PKEYs. In the collected data files, information in /$node/Infiniband/$device/pkey0 and pkey1 are missing:

No pkey found

I checked other files. IB drivers are installed correctly. so it's not likely that these 2 files are missing from the vm.

Then I checked the diagnostics.sh and figured that the file path might be wrong. 

The correct path for pkey (in my case) is:

/sys/class/infiniband/mlx5_0/ports/1/pkeys/0

The script is looking for:

Line 254  if [ -f "$device/ports/pkeys/0" ]; then

**Comment by tlcyr4** [comment]
Looks like the problem here is that the tool doesn't account for the different filesystem structure on HC44, and that size isn't included in the testing pipeline. I'll get started fixing both of those issues.
